---

name: Host provisioning
hosts: netology
tasks:

  - name: Upgrade pip
    become: true
    ansible.builtin.pip:
      name: pip
      state: latest
      executable: pip3
      extra_args: '--upgrade'

  - name: Install Ansible
    become: true
    ansible.builtin.pip:
      name: ansible
      state: latest
      executable: pip3

  - name: Install Git
    become: true
    ansible.builtin.yum:
      name: git
      state: latest
        
